[package]
name = "sombra-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sombra = { path = "../sombra" }
axum = "0.6"
shuttle-axum = "0.30"
shuttle-runtime = "0.30"
tokio = "1.28"
thiserror.workspace = true
serde.workspace = true
serde_derive.workspace = true
